### ISSUE TITLE
如果有两个请求 而且setCach 都设置为true  , 在第一个请求完成后,在进行第二个请求, 第二个请求则会出错

### ISSUE THREAD

**Issue by NiLuogege** [wzgiceman/RxjavaRetrofitDemo-master#16]
如果有两个请求 而且setCach 都设置为true  , 在第一个请求完成后,在进行第二个请求, 第二个请求则会出错

报错如下
02-15 18:00:10.350 11646-14550/? D/OkHttp: <-- HTTP FAILED: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: COOKIE_RESULTE._id (code 1555)
02-15 18:00:10.350 11646-14550/? D/OkHttp: #################################################################
02-15 18:00:10.350 11646-14550/? D/OkHttp: Error Code : 1555 (SQLITE_CONSTRAINT_PRIMARYKEY)
02-15 18:00:10.350 11646-14550/? D/OkHttp: Caused By : Abort due to constraint violation.
02-15 18:00:10.350 11646-14550/? D/OkHttp: 	(UNIQUE constraint failed: COOKIE_RESULTE._id (code 1555))
02-15 18:00:10.350 11646-14550/? D/OkHttp: #################################################################

**Comment by wzgiceman** [comment]
你这个问题应该是ID标识出问题了，你两个接口是走的同一个地址吗？

**Comment by NiLuogege** [comment]
同一个地址?你指的是同一个URL吗?  URL是不同的.    这个问题确实是ID冲突引起的,建表时我把id字段去掉的话就是可以的.



------------------ 原始邮件 ------------------
发件人: "wzgiceman";<notifications@github.com>;
发送时间: 2017年3月6日(星期一) 上午9:30
收件人: "wzgiceman/RxjavaRetrofitDemo-master"<RxjavaRetrofitDemo-master@noreply.github.com>; 
抄送: "河里的枇杷树"<835350313@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [wzgiceman/RxjavaRetrofitDemo-master] 如果有两个请求 而且setCach 都设置为true , 在第一个请求完成后,在进行第二个请求, 第二个请求则会出错 (#16)




你这个问题应该是ID标识出问题了，你两个接口是走的同一个地址吗？
