### ISSUE TITLE
下载功能

### ISSUE THREAD

**Issue by cyt1030** [wzgiceman/RxjavaRetrofitDemo-master#2]
下载器  ：正在下载的任务返回到上层， 再进去 进度条又从0开始  而实际上 后台还在继续下载过程中

**Comment by wzgiceman** [comment]
退出下载界面，下载已经暂停，我没有做复原处理，因为在httpdownmanager中pause和stop需要将downinfo信息写入到本地数据库中，这里需要自己添加你工程的数据库（更加灵活），然后再一次进入的时候读取downinfo的state状态值，显示就行了。

**Comment by wzgiceman** [comment]
初衷：我没有做复原处理，因为在httpdownmanager中pause和stop需要将downinfo信息写入到本地数据库中，这里需要自己添加你工程的数据库（更加灵活），然后再一次进入的时候读取downinfo的state状态值，显示就行了，但是既然你提出这个问题，我用greendao处理数据库，完善了这个逻辑
