### ISSUE TITLE
每个接口都要一个回调 这样 是不是 很繁琐 ？ 如果我同时请求多个 接口 不快疯掉了

### ISSUE THREAD

**Issue by cyt1030** [wzgiceman/RxjavaRetrofitDemo-master#4]
每个接口都要一个回调 这样 是不是 很繁琐 ？ 如果我同时请求多个 接口 不快疯掉了

**Comment by wzgiceman** [comment]
如果要使用Gson自动转换，就必须是一一对应的，没办法解决；如果你不想使用这种封装，可以使用我的变种工程，去掉Gson自动返回，改用String返回，然后统一通过接口判断：demo地址：https://github.com/wzgiceman/RxjavaRetrofitDemo-string-master
原理和之前的一样，不过是替换了Gson转换逻辑，后续会出相关的博客介绍，欢迎关注
