### ISSUE TITLE
没有看到其他取消订阅的地方，只有在onCancelProgress这里面取消了。

### ISSUE THREAD

**Issue by githubityu** [wzgiceman/RxjavaRetrofitDemo-master#7]
@Override
    public void onCancelProgress() {
        if (!this.isUnsubscribed()) {
            this.unsubscribe();
        }
        Logger.e(TAG+"onCancelProgress");
    }

**Comment by wzgiceman** [comment]
默认是rxlifecycle自动取消机制，这里cancel是手动触发，如果你需要外部也有这样的接口，可以直接调用sub的unsubscribe方法
