### ISSUE TITLE
没有找到DaoMaster这个数据库操作类啊

### ISSUE THREAD

**Issue by dongdongge** [wzgiceman/RxjavaRetrofitDemo-master#8]
大神，我没有找到DaoMaster这个数据库操作类啊，请指点下

**Comment by wzgiceman** [comment]
这个是greendao自动生成的类，build下工程就有了

**Comment by dongdongge** [comment]
谢谢，已经可以运行了，





------------------ 原始邮件 ------------------
发件人: "wzgiceman";<notifications@github.com>;
发送时间: 2016年11月28日(星期一) 中午1:16
收件人: "wzgiceman/RxjavaRetrofitDemo-master"<RxjavaRetrofitDemo-master@noreply.github.com>; 
抄送: "冬冬哥"<625324231@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [wzgiceman/RxjavaRetrofitDemo-master] 没有找到DaoMaster这个数据库操作类啊 (#8)




Closed #8.
