### ISSUE TITLE
像gradle里面的版本依赖能不能确定某个版本呢

### ISSUE THREAD

**Issue by yeyueduxing** [wzgiceman/RxjavaRetrofitDemo-master#9]
我的SDK版本是23（原谅我，并没有升到最新版本）。这边的版本依赖都是用+号来获取最新的，然后出现各种SDK25..0.0的，说真的，为了一个DEMO更新SDK太麻烦了。然后还得花时间找各种依赖库的版本号，一个+号，根本找不到版本号具体是什么，找的了版本号，运行起来还是错误。希望能把版本号确定一个比较好。

真实项目开发中版本号一定要固定，不然因为依赖库的更新导致某种不可预估的问题就坑爹了，碰到好几次这种问题了

**Comment by wzgiceman** [comment]
恩，准备做成moudel依赖的方式，将不会有这样的问题了！
